-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyiDlYO41FDgTjt/Q
kg2kRCV5kxntfEuwBIzEm0duNnqgCgYIKoZIzj0DAQehRANCAASLDnopdRvHy4wS
CWTGNf9MjnFNUKfhkhBQRzmRUS4fSayYQnO/6C0pgxnfI04xHDkvlyyQTWrwk9l0
PGniSDRI
-----END PRIVATE KEY-----